version: "3"
services:
  api:
    image: shanyue/whoami
    ports:
      - 8888:3000
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  location:
    image: nginx:alpine
    ports:
      - 8100:80
    volumes:
      - ./location.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  location2:
    image: nginx:alpine
    ports:
      - 8200:80
    volumes:
      - ./location2.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order1:
    image: nginx:alpine
    ports:
      - 8300:80
    volumes:
      - ./order1.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order2:
    image: nginx:alpine
    ports:
      - 8400:80
    volumes:
      - ./order2.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order3:
    image: nginx:alpine
    ports:
      - 8500:80
    volumes:
      - ./order3.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order4:
    image: nginx:alpine
    ports:
      - 8600:80
    volumes:
      - ./order4.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  proxy:
    image: nginx:alpine
    ports:
      - 8700:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
