version: "3"
services:
  single-app:
    build:
      context: .
      dockerfile: simple.Dockerfile
      args:
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - ENDPOINT
    ports:
      - 5200:80
