version: "3"

services:
  # 改镜像会暴露出自身的 `header` 信息
  blog:
    build:
        context: .
        dockerfile: blog.Dockerfile
    labels:
      # 设置Host 为 localhost 进行域名访问
      - traefik.http.routers.blog.rule=Host(`blog.cra.merlin218.top`)
      # 开启HTTPS
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=le
# 使用已存在的 traefik 的 network
networks:
  default:
    external:
      name: traefik_default
